version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest
      - run:
          name: Run tests
          command: |
            pytest --junitxml=test-results/junit.xml TestTriangle.py
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build:
    jobs:
      - build-and-test

